### ISSUE TITLE
Depth zip download error

### ISSUE THREAD

**Issue by jh27kim** [jinlinyi/SparsePlanes#11]
OneDrive keeps throwing an error when downloading about 75%.
Could you please verify whether the error is on my end or on the server's end ?
Thank you

![image](https://github.com/jinlinyi/SparsePlanes/assets/58447982/87d86ee7-7809-47ad-b583-9298594a6f8a)

**Comment by jinlinyi** [comment]
Hi, thanks for pointing out. I've updated the dropbox link and included a google drive alternative link.
