### ISSUE TITLE
how many images I can input ?

### ISSUE THREAD

**Issue by KirillHiddleston** [jinlinyi/SparsePlanes#2]
Hello nice job)
Have you tested this on more than two images ?
--img-list /path/to/img_list.txt \
 
img_list.txt:
  > img1.png
  > img2.png
  > img3.png
......
what about structure img_list.txt

Can I add 3 or 10 images ?

**Comment by jinlinyi** [comment]
Our paper mainly focused on reconstruction from two sparse images. This inference code only supports image pairs as input right now.

**Comment by jinlinyi** [comment]
I've updated the readme and added an example image_list.txt. Sorry for the confusion.

**Comment by KirillHiddleston** [comment]
@jinlinyi could you tell me why there are only two images. Have you thought about making for more two images?
I'm working on a similar project planar surface reconstruction, but with panoramic image

**Comment by jinlinyi** [comment]
@KirillHiddleston Great question! One way to handle 3+ views is as in incremental SfM: merge two views with the most plane correspondences, average the plane parameters, then repeat this with other views. This incremental method was done for Figure 7 in our paper. More views may need a learned system on top; we are working towards one that handles multiple views and trains end-to-end.
