### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by KirillHiddleston** [jinlinyi/SparsePlanes#3]
No module named 'KMSolver'
No module named 'seaborn'
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
u need uninstall numpy 1.19.2 and change to pip install numpy==1.20.0 and 
no problem install seaborn

How to install KMSolver ????

**Comment by jinlinyi** [comment]
Oops, I forgot to upload KMSolver because of .gitignore. Added now!

**Comment by KirillHiddleston** [comment]
i need reinstall pip install -e .?

**Comment by zhang-21** [comment]
> i need reinstall pip install -e .?

Hello, could you give some advices for the problem
“No module named 'KMSolver”

**Comment by jinlinyi** [comment]
> > i need reinstall pip install -e .?
> 
> Hello, could you give some advices for the problem “No module named 'KMSolver”



[KMSolver.cpython-37m-x86_64-linux-gnu.so](https://github.com/jinlinyi/SparsePlanes/blob/main/sparsePlane/KMSolver.cpython-37m-x86_64-linux-gnu.so)

I used the above KMSolver (already in the repo) from https://github.com/caizhongang/MessyTable#environment

**Comment by zhang-21** [comment]
> > > i need reinstall pip install -e .?
> > 
> > 
> > Hello, could you give some advices for the problem “No module named 'KMSolver”
> 
> [KMSolver.cpython-37m-x86_64-linux-gnu.so](https://github.com/jinlinyi/SparsePlanes/blob/main/sparsePlane/KMSolver.cpython-37m-x86_64-linux-gnu.so)
> 
> I used the above KMSolver (already in the repo) from https://github.com/caizhongang/MessyTable#environment

Frankly, I got this error when setting up the environment of PlaneFormers[https://github.com/samiragarwala/PlaneFormers](url)
I'm trying to run the code on my own computer with 4090 GPU, python=3.9, CUDA 11.7 with PyTorch 1.13, Detectron 2 == 0.6
I have got the .so file using "git clone" according to your instruction.
I wonder if this problem is caused by inconsistent python versions?

**Comment by jinlinyi** [comment]
> > > > i need reinstall pip install -e .?
> > > 
> > > 
> > > Hello, could you give some advices for the problem “No module named 'KMSolver”
> > 
> > 
> > [KMSolver.cpython-37m-x86_64-linux-gnu.so](https://github.com/jinlinyi/SparsePlanes/blob/main/sparsePlane/KMSolver.cpython-37m-x86_64-linux-gnu.so)
> > I used the above KMSolver (already in the repo) from https://github.com/caizhongang/MessyTable#environment
> 
> Frankly, I got this error when setting up the environment of PlaneFormers[https://github.com/samiragarwala/PlaneFormers](url) I'm trying to run the code on my own computer with 4090 GPU, python=3.9, CUDA 11.7 with PyTorch 1.13, Detectron 2 == 0.6 I have got the .so file using "git clone" according to your instruction. I wonder if this problem is caused by inconsistent python versions?

It has to be python 3.7.
