### ISSUE TITLE
Dataset download links seem extremely slow

### ISSUE THREAD

**Issue by Pushkar2307** [jinlinyi/SparsePlanes#8]
Hi, thanks for sharing this amazing work!

The dataset download link are extremely slow for me. I tried on multiple networks.

Is there an alternative link to download the dataset?

Thanks,
Pushkar

**Comment by jinlinyi** [comment]
Hi Pushkar, 

Thank you for your interest in our dataset. There is a network issue going on inside our university. Here are alternative links from dropbox.
[mp3d_planercnn_json.zip](https://www.dropbox.com/s/uqkcaaoayd0me8e/mp3d_planercnn_json.zip?dl=0)
[rgb.zip](https://www.dropbox.com/s/po09x0aovog9oe1/rgb.zip?dl=0)
[observations.zip](https://www.dropbox.com/s/otea8zdyadmxj15/observations.zip?dl=0)
[planes_ply_mp3dcoord_refined.zip](https://www.dropbox.com/s/84ulrsk47b72nfv/planes_ply_mp3dcoord_refined.zip?dl=0)
[cameras.zip](https://www.dropbox.com/s/ul1v2vrlzl4voxj/cameras.zip?dl=0)

Hope these help!

**Comment by Pushkar2307** [comment]
Hi, thank you for the quick help! These links work fine :)

Do you have a Dropbox link for the pretrained model as well? Sorry for the trouble.

Thanks,
Pushkar

**Comment by jinlinyi** [comment]
Here is the link https://www.dropbox.com/sh/7itozhd5kvql7n6/AABTanMoyJpcwBnkZIRiRSt3a?dl=0
